### Post 'Hello!"
POST http://localhost:8080/add
Content-Type: application/json

{
  "id": 2,
  "taskName": "TestFromProgram",
  "endDate": "2022-05-08",
  "repeat": 2,
  "canSkip": false,
  "repeatDays": 7,
  "tag": null,
  "color": 0,
  "note": null
}

### Post2
POST http://localhost:8080/add
Content-Type: application/json

{
  "id":1,
  "taskName":"TestFromProgram1",
  "endDate":"2022-05-09",
  "repeat":3,
  "canSkip": true,
  "repeatDays": 2
}

### Complete Task Post
POST http://localhost:8080/display/complete
Content-Type: application/json

"98dbab79-c980-492c-ab5c-64e0822f0ba0"

### Skip Task Post
POST http://localhost:8080/display/skip
Content-Type: application/json

"601cf4f2-6a35-4caf-b7e6-fd5be9feba31"

### End Day
POST http://localhost:8080/dayEnd
Content-Type: application/json

### Get all the messages
GET http://localhost:8080/


### Get all the messages
GET http://localhost:8080/display
